use_frameworks!

platform :ios, '8.0'

target 'AntiReviewHandler_Example' do
  pod 'AntiReviewHandler', :path => '../'

  target 'AntiReviewHandler_Tests' do
    inherit! :search_paths

    
  end
end
